{"name": "test_add_failure_reason", "status": "passed", "description": "\n        P2 #13: AÃ±adir motivo de fallo\n        ", "start": 1760550107673, "stop": 1760550119455, "uuid": "0a224fde-c6d7-4776-ba1d-66fb7c6cb915", "historyId": "d6fa5ef90c871848e87d0edf946b7c11", "testCaseId": "d6fa5ef90c871848e87d0edf946b7c11", "fullName": "tests.test_rider_functionality.TestRiderFunctionality#test_add_failure_reason", "labels": [{"name": "tag", "value": "test_id('P2-013')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_rider_functionality"}, {"name": "subSuite", "value": "TestRiderFunctionality"}, {"name": "host", "value": "L43429"}, {"name": "thread", "value": "21848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_rider_functionality"}]}